theme = "ayu_mirage"

[editor]
color-modes = true
auto-pairs = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
auto-signature-help	= true
display-signature-help-docs	= true

[keys.normal]
# Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph", "collapse_selection"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph", "collapse_selection"]

V = ["select_mode", "extend_to_line_bounds"]

# Make j and k behave as they do Vim when soft-wrap is enabled
up = "move_line_up"
down = "move_line_down"

C-right = ["move_next_word_start"]
C-left = ["move_prev_word_start"]
C-up = "goto_prev_paragraph"
C-down = "goto_next_paragraph"

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]

# Beginning/end of line
"^" = "goto_line_start"
"$" = "goto_line_end"

# Vim-like C and D commands
C = ["extend_to_line_end", "change_selection"]
D = ["extend_to_line_end", "delete_selection"]

# Alternative binding for native Helix C functionality (copy selection to next line)
C-c = "copy_selection_on_next_line"

[keys.insert]
C-left = "move_prev_word_start"
C-right = "move_next_word_start"
C-up = "goto_prev_paragraph"
C-down = "goto_next_paragraph"

[keys.select]
# Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph", "collapse_selection"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph", "collapse_selection"]

# Make selecting lines in visual mode behave sensibly
up = ["extend_line_up"]
down = ["extend_line_down"]

C-left = "extend_prev_word_start"
C-right = "extend_next_word_start"
C-up = ["extend_to_line_bounds", "goto_prev_paragraph"]
C-down = ["extend_to_line_bounds", "goto_next_paragraph"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

# Beginning/end of line
"^" = "extend_to_line_start"
"$" = "extend_to_line_end"
