last_modified = "2025-09-07T06:03:43.403326737Z"

[public_key]
version = 0
algorithm = "Ed25519"
signature = "28AfVn6BueztKweqsFo5Kbem41wBEvzou3wxVsmV1Vd8cSz993X7EvczSvANTETBS9hcs2TzAQJWeThFYP18KgFX"
key = "BS5Dz4HCUkEu1XYU6UXB7UNn3qVQcdM1UoC86a7r4C6y"
